// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/metastore.proto

/*
Package metastore is a generated protocol buffer package.

It is generated from these files:
	protobuf/metastore.proto

It has these top-level messages:
	RequestStatus
	Namespace
	Cookie
	Id
	Database
	CreateDatabaseRequest
	GetDatabaseRequest
	GetDatabaseResponse
	ListDatabasesRequest
	DropDatabaseRequest
*/
package metastore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestStatus_Status int32

const (
	RequestStatus_OK       RequestStatus_Status = 0
	RequestStatus_ERROR    RequestStatus_Status = 1
	RequestStatus_NOTFOUND RequestStatus_Status = 2
	RequestStatus_CONFLICT RequestStatus_Status = 3
)

var RequestStatus_Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
	2: "NOTFOUND",
	3: "CONFLICT",
}
var RequestStatus_Status_value = map[string]int32{
	"OK":       0,
	"ERROR":    1,
	"NOTFOUND": 2,
	"CONFLICT": 3,
}

func (x RequestStatus_Status) String() string {
	return proto.EnumName(RequestStatus_Status_name, int32(x))
}
func (RequestStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// General status for results
type RequestStatus struct {
	Status RequestStatus_Status `protobuf:"varint,1,opt,name=status,enum=metastore.RequestStatus_Status" json:"status,omitempty"`
	Error  string               `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *RequestStatus) Reset()                    { *m = RequestStatus{} }
func (m *RequestStatus) String() string            { return proto.CompactTextString(m) }
func (*RequestStatus) ProtoMessage()               {}
func (*RequestStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestStatus) GetStatus() RequestStatus_Status {
	if m != nil {
		return m.Status
	}
	return RequestStatus_OK
}

func (m *RequestStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Every object belongs to a namespace.
type Namespace struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Namespace) Reset()                    { *m = Namespace{} }
func (m *Namespace) String() string            { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()               {}
func (*Namespace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Cookie is supposed to be used to associate multiple requests to a single session.
// The value of the cookie is likely to be printed in logs so it shouldn't contain
// any sensitive information.
// Metastore service does not interpret the cookie but may print it in its logs.
type Cookie struct {
	Cookie string `protobuf:"bytes,1,opt,name=cookie" json:"cookie,omitempty"`
}

func (m *Cookie) Reset()                    { *m = Cookie{} }
func (m *Cookie) String() string            { return proto.CompactTextString(m) }
func (*Cookie) ProtoMessage()               {}
func (*Cookie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Cookie) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

// Objects belong to a specific namespace and have unique name and unique ID
// in the namespace.
type Id struct {
	Namespace *Namespace `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Name      string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Id        string     `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Id) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Id) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Database is a namespace for tables.
// Original Metastore Database object also had location and owner information.
// These can be represented using parameters if needed since the current
// metastore service does n;t interpret either Location or Owner info.
type Database struct {
	Id         *Id               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Database) Reset()                    { *m = Database{} }
func (m *Database) String() string            { return proto.CompactTextString(m) }
func (*Database) ProtoMessage()               {}
func (*Database) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Database) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Database) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// Create a new database.
// Request should have the namespace and the name of the database.
// The name should be unique within the namespace
// unique ID is assigned by the service.
type CreateDatabaseRequest struct {
	Id         *Id               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Cookie     *Cookie           `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
	Parameters map[string]string `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateDatabaseRequest) Reset()                    { *m = CreateDatabaseRequest{} }
func (m *CreateDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDatabaseRequest) ProtoMessage()               {}
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateDatabaseRequest) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateDatabaseRequest) GetCookie() *Cookie {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func (m *CreateDatabaseRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// Request to get database by its ID.
type GetDatabaseRequest struct {
	Id     *Id     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Cookie *Cookie `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
}

func (m *GetDatabaseRequest) Reset()                    { *m = GetDatabaseRequest{} }
func (m *GetDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDatabaseRequest) ProtoMessage()               {}
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetDatabaseRequest) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetDatabaseRequest) GetCookie() *Cookie {
	if m != nil {
		return m.Cookie
	}
	return nil
}

type GetDatabaseResponse struct {
	Database *Database      `protobuf:"bytes,1,opt,name=database" json:"database,omitempty"`
	Status   *RequestStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *GetDatabaseResponse) Reset()                    { *m = GetDatabaseResponse{} }
func (m *GetDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDatabaseResponse) ProtoMessage()               {}
func (*GetDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetDatabaseResponse) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *GetDatabaseResponse) GetStatus() *RequestStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Request to get list of databases
type ListDatabasesRequest struct {
	Namespace   *Namespace `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Cookie      *Cookie    `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
	NamePattern string     `protobuf:"bytes,3,opt,name=name_pattern,json=namePattern" json:"name_pattern,omitempty"`
}

func (m *ListDatabasesRequest) Reset()                    { *m = ListDatabasesRequest{} }
func (m *ListDatabasesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDatabasesRequest) ProtoMessage()               {}
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListDatabasesRequest) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *ListDatabasesRequest) GetCookie() *Cookie {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func (m *ListDatabasesRequest) GetNamePattern() string {
	if m != nil {
		return m.NamePattern
	}
	return ""
}

// Request to drop a database.
// Dropping a database also drops all objects contained in the database
type DropDatabaseRequest struct {
	Id     *Id     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Cookie *Cookie `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
}

func (m *DropDatabaseRequest) Reset()                    { *m = DropDatabaseRequest{} }
func (m *DropDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*DropDatabaseRequest) ProtoMessage()               {}
func (*DropDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DropDatabaseRequest) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DropDatabaseRequest) GetCookie() *Cookie {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestStatus)(nil), "metastore.RequestStatus")
	proto.RegisterType((*Namespace)(nil), "metastore.Namespace")
	proto.RegisterType((*Cookie)(nil), "metastore.Cookie")
	proto.RegisterType((*Id)(nil), "metastore.Id")
	proto.RegisterType((*Database)(nil), "metastore.Database")
	proto.RegisterType((*CreateDatabaseRequest)(nil), "metastore.CreateDatabaseRequest")
	proto.RegisterType((*GetDatabaseRequest)(nil), "metastore.GetDatabaseRequest")
	proto.RegisterType((*GetDatabaseResponse)(nil), "metastore.GetDatabaseResponse")
	proto.RegisterType((*ListDatabasesRequest)(nil), "metastore.ListDatabasesRequest")
	proto.RegisterType((*DropDatabaseRequest)(nil), "metastore.DropDatabaseRequest")
	proto.RegisterEnum("metastore.RequestStatus_Status", RequestStatus_Status_name, RequestStatus_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Metastore service

type MetastoreClient interface {
	// Create a new database
	CreateDabatase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
	// Get database information
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
	// Get collection of databases
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (Metastore_ListDatabasesClient, error)
	// Destroy a database
	DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*RequestStatus, error)
}

type metastoreClient struct {
	cc *grpc.ClientConn
}

func NewMetastoreClient(cc *grpc.ClientConn) MetastoreClient {
	return &metastoreClient{cc}
}

func (c *metastoreClient) CreateDabatase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	out := new(GetDatabaseResponse)
	err := grpc.Invoke(ctx, "/metastore.Metastore/CreateDabatase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metastoreClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	out := new(GetDatabaseResponse)
	err := grpc.Invoke(ctx, "/metastore.Metastore/GetDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metastoreClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (Metastore_ListDatabasesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Metastore_serviceDesc.Streams[0], c.cc, "/metastore.Metastore/ListDatabases", opts...)
	if err != nil {
		return nil, err
	}
	x := &metastoreListDatabasesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Metastore_ListDatabasesClient interface {
	Recv() (*Database, error)
	grpc.ClientStream
}

type metastoreListDatabasesClient struct {
	grpc.ClientStream
}

func (x *metastoreListDatabasesClient) Recv() (*Database, error) {
	m := new(Database)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metastoreClient) DropDatabase(ctx context.Context, in *DropDatabaseRequest, opts ...grpc.CallOption) (*RequestStatus, error) {
	out := new(RequestStatus)
	err := grpc.Invoke(ctx, "/metastore.Metastore/DropDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Metastore service

type MetastoreServer interface {
	// Create a new database
	CreateDabatase(context.Context, *CreateDatabaseRequest) (*GetDatabaseResponse, error)
	// Get database information
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error)
	// Get collection of databases
	ListDatabases(*ListDatabasesRequest, Metastore_ListDatabasesServer) error
	// Destroy a database
	DropDatabase(context.Context, *DropDatabaseRequest) (*RequestStatus, error)
}

func RegisterMetastoreServer(s *grpc.Server, srv MetastoreServer) {
	s.RegisterService(&_Metastore_serviceDesc, srv)
}

func _Metastore_CreateDabatase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetastoreServer).CreateDabatase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metastore.Metastore/CreateDabatase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetastoreServer).CreateDabatase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metastore_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetastoreServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metastore.Metastore/GetDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetastoreServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metastore_ListDatabases_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDatabasesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetastoreServer).ListDatabases(m, &metastoreListDatabasesServer{stream})
}

type Metastore_ListDatabasesServer interface {
	Send(*Database) error
	grpc.ServerStream
}

type metastoreListDatabasesServer struct {
	grpc.ServerStream
}

func (x *metastoreListDatabasesServer) Send(m *Database) error {
	return x.ServerStream.SendMsg(m)
}

func _Metastore_DropDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetastoreServer).DropDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metastore.Metastore/DropDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetastoreServer).DropDatabase(ctx, req.(*DropDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metastore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metastore.Metastore",
	HandlerType: (*MetastoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDabatase",
			Handler:    _Metastore_CreateDabatase_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _Metastore_GetDatabase_Handler,
		},
		{
			MethodName: "DropDatabase",
			Handler:    _Metastore_DropDatabase_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDatabases",
			Handler:       _Metastore_ListDatabases_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/metastore.proto",
}

func init() { proto.RegisterFile("protobuf/metastore.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcd, 0x8e, 0x12, 0x41,
	0x10, 0x76, 0x06, 0x77, 0xc2, 0x14, 0x3f, 0x62, 0x81, 0x66, 0x42, 0xb2, 0x2e, 0xb6, 0x17, 0xbc,
	0xb0, 0x04, 0x0f, 0x6b, 0x4c, 0xbc, 0x2c, 0xec, 0xae, 0x44, 0x04, 0xd2, 0xbb, 0xde, 0x8c, 0x9b,
	0x06, 0xda, 0x84, 0xb0, 0x30, 0x63, 0x77, 0x63, 0xdc, 0x27, 0xd1, 0x97, 0xf0, 0x1d, 0x7c, 0x26,
	0x9f, 0xc0, 0x4c, 0xcf, 0x0f, 0x8d, 0x19, 0xb2, 0x6a, 0xc2, 0x89, 0xea, 0xaa, 0xaf, 0xeb, 0xeb,
	0xaa, 0xaf, 0x8a, 0x01, 0x2f, 0x10, 0xbe, 0xf2, 0x27, 0xeb, 0x4f, 0xc7, 0x4b, 0xae, 0x98, 0x54,
	0xbe, 0xe0, 0x2d, 0xed, 0x42, 0x37, 0x75, 0x90, 0x6f, 0x16, 0x94, 0x28, 0xff, 0xbc, 0xe6, 0x52,
	0x5d, 0x2a, 0xa6, 0xd6, 0x12, 0x4f, 0xc0, 0x91, 0xda, 0xf2, 0xac, 0x86, 0xd5, 0x2c, 0x77, 0x8e,
	0x5a, 0x9b, 0xeb, 0x5b, 0xc8, 0x56, 0xf4, 0x43, 0x63, 0x38, 0xd6, 0xe0, 0x80, 0x0b, 0xe1, 0x0b,
	0xcf, 0x6e, 0x58, 0x4d, 0x97, 0x46, 0x07, 0x72, 0x02, 0x4e, 0x9c, 0xd8, 0x01, 0x7b, 0xf4, 0xb6,
	0x72, 0x0f, 0x5d, 0x38, 0x38, 0xa3, 0x74, 0x44, 0x2b, 0x16, 0x16, 0x21, 0x3f, 0x1c, 0x5d, 0x9d,
	0x8f, 0xde, 0x0f, 0x7b, 0x15, 0x3b, 0x3c, 0x75, 0x47, 0xc3, 0xf3, 0x41, 0xbf, 0x7b, 0x55, 0xc9,
	0x91, 0x23, 0x70, 0x87, 0x6c, 0xc9, 0x65, 0xc0, 0xa6, 0x1c, 0x11, 0xee, 0xaf, 0xd8, 0x92, 0xeb,
	0x27, 0xb9, 0x54, 0xdb, 0xa4, 0x01, 0x4e, 0xd7, 0xf7, 0x17, 0x73, 0x8e, 0x8f, 0xc1, 0x99, 0x6a,
	0x2b, 0x8e, 0xc7, 0x27, 0xf2, 0x01, 0xec, 0xfe, 0x0c, 0x3b, 0xe0, 0xae, 0x92, 0x44, 0x1a, 0x50,
	0xe8, 0xd4, 0x8c, 0x9a, 0x52, 0x12, 0xba, 0x81, 0xa5, 0x7c, 0xf6, 0x86, 0x0f, 0xcb, 0x60, 0xcf,
	0x67, 0x5e, 0x4e, 0x7b, 0xec, 0xf9, 0x8c, 0xfc, 0xb0, 0x20, 0xdf, 0x63, 0x8a, 0x4d, 0x98, 0xe4,
	0x78, 0xa8, 0x83, 0x51, 0xf6, 0x92, 0x91, 0xbd, 0x3f, 0x0b, 0xb1, 0xd8, 0x05, 0x08, 0x98, 0x60,
	0x4b, 0xae, 0xb8, 0x90, 0x9e, 0xdd, 0xc8, 0x35, 0x0b, 0x9d, 0x67, 0x06, 0x2c, 0xc9, 0xd3, 0x1a,
	0xa7, 0xa8, 0xb3, 0x95, 0x12, 0xb7, 0xd4, 0xb8, 0x56, 0x7f, 0x0d, 0x0f, 0xfe, 0x08, 0x63, 0x05,
	0x72, 0x0b, 0x7e, 0x1b, 0x97, 0x1d, 0x9a, 0xa1, 0x0a, 0x5f, 0xd8, 0xcd, 0x3a, 0x79, 0x7a, 0x74,
	0x78, 0x65, 0xbf, 0xb4, 0xc8, 0x2f, 0x0b, 0x1e, 0x75, 0x05, 0x67, 0x8a, 0x27, 0x6c, 0xb1, 0x9c,
	0x77, 0x3d, 0xfe, 0x79, 0xda, 0x5e, 0x5b, 0x43, 0x1e, 0x1a, 0x90, 0x48, 0x81, 0xa4, 0xe3, 0x38,
	0xde, 0xaa, 0x33, 0xa7, 0xeb, 0x6c, 0x9b, 0xf0, 0x2c, 0xfe, 0x7d, 0x16, 0xfd, 0x11, 0xf0, 0x82,
	0xab, 0xbd, 0x15, 0x4c, 0xbe, 0x42, 0x75, 0x2b, 0xbf, 0x0c, 0xfc, 0x95, 0xe4, 0x78, 0x0c, 0xf9,
	0x59, 0xec, 0x8b, 0x69, 0xaa, 0x19, 0x6a, 0xd3, 0x14, 0x84, 0xed, 0x74, 0xeb, 0x22, 0x4a, 0x6f,
	0xd7, 0xd6, 0x25, 0xeb, 0x46, 0xbe, 0x5b, 0x50, 0x1b, 0xcc, 0x65, 0xca, 0x2d, 0x93, 0xe2, 0xfe,
	0x67, 0xde, 0xff, 0x41, 0xe2, 0xa7, 0x50, 0x0c, 0xef, 0x5d, 0x07, 0x4c, 0x29, 0x2e, 0x56, 0xf1,
	0x42, 0x14, 0x42, 0xdf, 0x38, 0x72, 0x91, 0x6b, 0xa8, 0xf6, 0x84, 0x1f, 0xec, 0xad, 0xeb, 0x9d,
	0x9f, 0x36, 0xb8, 0xef, 0x92, 0x20, 0x52, 0x28, 0x27, 0x73, 0x35, 0x61, 0x2a, 0xec, 0x66, 0xe3,
	0xae, 0x91, 0xab, 0x3f, 0x31, 0x10, 0x59, 0x02, 0x0e, 0xa0, 0x60, 0xb8, 0xf1, 0x70, 0x17, 0xfc,
	0xef, 0xb2, 0x5d, 0x40, 0x69, 0x4b, 0x2a, 0x34, 0xff, 0x54, 0xb3, 0x44, 0xac, 0x67, 0x8d, 0x4b,
	0xdb, 0xc2, 0x37, 0x50, 0x34, 0x3b, 0x8b, 0x26, 0x71, 0x46, 0xcb, 0xeb, 0x3b, 0xc7, 0xe8, 0x94,
	0x40, 0x75, 0xea, 0x2f, 0x5b, 0x6c, 0xe1, 0xdf, 0x4c, 0x36, 0xa0, 0x53, 0xdd, 0xd6, 0xcb, 0xd0,
	0x1c, 0x5b, 0x13, 0x47, 0x7f, 0x2e, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xf7, 0x94,
	0x49, 0x4a, 0x06, 0x00, 0x00,
}
