FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# hmsv2

hmsv2 is the new version of Hive Metastore API

## Databases [/db]

### Create a new Database [POST]

You may create your own database using this action. It takes a JSON
object containing a database information.

+ Request (application/json)

        {
            "catalog": "Name of the catalog for this database",
            "name": "Database name",
            "location": "Default top-level location of database objects"
            "properties": "Dictionary of database properties"
        }

    + Schema

            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                    "catalog": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                }
            }
            I
+ Response 201 (application/json)

    + Headers

            Location: /db/2
            Id: 3

    + Body

            {
            }

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]