# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import metastore_pb2 as metastore__pb2


class MetastoreStub(object):
  """Metastore service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateDabatase = channel.unary_unary(
        '/metastore.Metastore/CreateDabatase',
        request_serializer=metastore__pb2.CreateDatabaseRequest.SerializeToString,
        response_deserializer=metastore__pb2.GetDatabaseResponse.FromString,
        )
    self.GetDatabase = channel.unary_unary(
        '/metastore.Metastore/GetDatabase',
        request_serializer=metastore__pb2.GetDatabaseRequest.SerializeToString,
        response_deserializer=metastore__pb2.GetDatabaseResponse.FromString,
        )
    self.ListDatabases = channel.unary_stream(
        '/metastore.Metastore/ListDatabases',
        request_serializer=metastore__pb2.ListDatabasesRequest.SerializeToString,
        response_deserializer=metastore__pb2.Database.FromString,
        )
    self.DropDatabase = channel.unary_unary(
        '/metastore.Metastore/DropDatabase',
        request_serializer=metastore__pb2.DropDatabaseRequest.SerializeToString,
        response_deserializer=metastore__pb2.RequestStatus.FromString,
        )
    self.CreateTable = channel.unary_unary(
        '/metastore.Metastore/CreateTable',
        request_serializer=metastore__pb2.CreateTableRequest.SerializeToString,
        response_deserializer=metastore__pb2.GetTableResponse.FromString,
        )


class MetastoreServicer(object):
  """Metastore service
  """

  def CreateDabatase(self, request, context):
    """Create a new database
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDatabase(self, request, context):
    """Get database information
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListDatabases(self, request, context):
    """Get collection of databases
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DropDatabase(self, request, context):
    """Destroy a database
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTable(self, request, context):
    """Create a new table
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MetastoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateDabatase': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDabatase,
          request_deserializer=metastore__pb2.CreateDatabaseRequest.FromString,
          response_serializer=metastore__pb2.GetDatabaseResponse.SerializeToString,
      ),
      'GetDatabase': grpc.unary_unary_rpc_method_handler(
          servicer.GetDatabase,
          request_deserializer=metastore__pb2.GetDatabaseRequest.FromString,
          response_serializer=metastore__pb2.GetDatabaseResponse.SerializeToString,
      ),
      'ListDatabases': grpc.unary_stream_rpc_method_handler(
          servicer.ListDatabases,
          request_deserializer=metastore__pb2.ListDatabasesRequest.FromString,
          response_serializer=metastore__pb2.Database.SerializeToString,
      ),
      'DropDatabase': grpc.unary_unary_rpc_method_handler(
          servicer.DropDatabase,
          request_deserializer=metastore__pb2.DropDatabaseRequest.FromString,
          response_serializer=metastore__pb2.RequestStatus.SerializeToString,
      ),
      'CreateTable': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTable,
          request_deserializer=metastore__pb2.CreateTableRequest.FromString,
          response_serializer=metastore__pb2.GetTableResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'metastore.Metastore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
